# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
from Enggine.cari import Ui_cari
from Enggine.input import Ui_Input
from Enggine.export import Ui_Export
from Enggine.About import Ui_About
class Ui_MainWindow(object):
    def tampil(self):
        try :
            conn = sqlite3.connect('Data/peserta.db')
            c = conn.cursor()
            sql = "SELECT * FROM peserta"
            data = c.execute(sql)
            self.tabel.setRowCount(0)
            ########<koneksi dengan table>############## 
            for no_baris, baris_data in enumerate(data):
                self.tabel.insertRow(no_baris)
                for no_kolom, info in enumerate(baris_data):
                    self.tabel.setItem(no_baris, no_kolom, QtWidgets.QTableWidgetItem(str(info)))
            c.close()
            conn.close()
        except:
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Critical)
            msgbox.setWindowTitle('Warning')
            msgbox.setText('Data tidak ditemukan')
            keluar = msgbox.exec_()
    def buang(self):
        msgbox = QMessageBox()
        msgbox.setIcon(QMessageBox.Question)
        msgbox.setWindowTitle('Alert')
        msgbox.setText('apakah kamu ingin menghapus semua data ini..?')
        msgbox.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        tombol = msgbox.exec_()
        if tombol == QMessageBox.Yes:
            conn = sqlite3.connect('Data/peserta.db')
            c = conn.cursor()
            sql = "DELETE FROM peserta"
            c.execute(sql)
            conn.commit()
            c.close
            conn.close()
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Information)
            msgbox.setWindowTitle('Info')
            msgbox.setText('semua data telah terhapus')
            keluar = msgbox.exec_()
        else:
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Information)
            msgbox.setWindowTitle('info')
            msgbox.setText('penghapusan data dibatalkan')
            keluar = msgbox.exec_()
    def tambah(self):
        self.wnd = QtWidgets.QWidget()
        self.ui = Ui_Input()
        self.ui.setupUi(self.wnd)
        self.wnd.show()
    def cari(self):
        self.wnd = QtWidgets.QWidget()
        self.ui = Ui_cari()
        self.ui.setupUi(self.wnd)
        self.wnd.show()
    def ekspor(self):
        self.wnd = QtWidgets.QWidget()
        self.ui = Ui_Export()
        self.ui.setupUi(self.wnd)
        self.wnd.show()
    def tentang(self):
        self.wnd = QtWidgets.QWidget()
        self.ui = Ui_About()
        self.ui.setupUi(self.wnd)
        self.wnd.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 911, 600))
        self.label.setStyleSheet("background-color: #ffffff")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 911, 71))
        self.label_2.setStyleSheet("background-color: #cccccc;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tabel = QtWidgets.QTableWidget(self.centralwidget)
        self.tabel.setGeometry(QtCore.QRect(0, 70, 911, 531))
        self.tabel.setObjectName("tabel")
        self.tabel.setColumnCount(5)
        self.tabel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        item.setFont(font)
        self.tabel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        item.setFont(font)
        self.tabel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        item.setFont(font)
        self.tabel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        item.setFont(font)
        self.tabel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        item.setFont(font)
        self.tabel.setHorizontalHeaderItem(4, item)
        self.tabel.horizontalHeader().setDefaultSectionSize(181)
        self.Add = QtWidgets.QToolButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(10, 10, 80, 56))
        self.Add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add.setStyleSheet("border-radius:9px;")
        self.Add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Add.setIcon(icon)
        #############Tombol Add###############
        self.Add.clicked.connect(self.tambah)
        ######################################
        self.Add.setIconSize(QtCore.QSize(52, 52))
        self.Add.setObjectName("Add")
        self.Refresh = QtWidgets.QToolButton(self.centralwidget)
        self.Refresh.setGeometry(QtCore.QRect(120, 10, 80, 56))
        self.Refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Refresh.setStyleSheet("border-radius:9px;")
        self.Refresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh.setIcon(icon1)
        self.Refresh.setIconSize(QtCore.QSize(52, 52))
        self.Refresh.setObjectName("Refresh")
        #########Tombol Refresh#########
        self.Refresh.clicked.connect(self.tampil)
        #############################
        self.Search = QtWidgets.QToolButton(self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(230, 10, 80, 56))
        self.Search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Search.setStyleSheet("border-radius:9px;")
        self.Search.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Search.setIcon(icon2)
        ###########Tombol Search###########
        self.Search.clicked.connect(self.cari)
        ##################################
        self.Search.setIconSize(QtCore.QSize(52, 52))
        self.Search.setObjectName("Search")
        self.Export = QtWidgets.QToolButton(self.centralwidget)
        self.Export.setGeometry(QtCore.QRect(340, 10, 80, 56))
        self.Export.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Export.setStyleSheet("border-radius:9px;")
        self.Export.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/publish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Export.setIcon(icon3)
        ############Tombol Ekspor#######
        self.Export.clicked.connect(self.ekspor)
        ################################
        self.Export.setIconSize(QtCore.QSize(52, 52))
        self.Export.setObjectName("Export")
        self.Info = QtWidgets.QToolButton(self.centralwidget)
        self.Info.setGeometry(QtCore.QRect(450, 10, 80, 56))
        self.Info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Info.setStyleSheet("border-radius:9px;")
        self.Info.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Info.setIcon(icon4)
        self.Info.setIconSize(QtCore.QSize(52, 52))
        self.Info.setObjectName("Info")
        ###########Tombol_Info################
        self.Info.clicked.connect(self.tentang)
        ######################################
        self.Trash = QtWidgets.QToolButton(self.centralwidget)
        self.Trash.setGeometry(QtCore.QRect(820, 10, 80, 56))
        #########tombol Format################
        self.Trash.clicked.connect(self.buang)
        ######################################
        self.Trash.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Trash.setStyleSheet("border-radius:9px;")
        self.Trash.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Trash.setIcon(icon5)
        self.Trash.setIconSize(QtCore.QSize(52, 52))
        self.Trash.setObjectName("Trash")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Daftar Peserta Vaksinasi"))
        item = self.tabel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.tabel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NIK"))
        item = self.tabel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Jenis Kelamin"))
        item = self.tabel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "No.HP"))
        item = self.tabel.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Alamat"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
