# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cari_peserta2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3
from PyQt5.QtWidgets import QDialogButtonBox

class Ui_cari(object):
    def pencarian(self):
        try :
            Nama = self.Search_text.text()
            conn = sqlite3.connect('Data/peserta.db')
            c = conn.cursor()
            sql = "SELECT * from peserta WHERE Nama_Peserta='%s'"%(Nama)
            data = c.execute(sql)
            result = c.fetchone()
            self.Nama.setPlainText(str(result[0]))
            self.NIK.setPlainText(str(result[1]))
            self.Kelamin.setCurrentText(str(result[2]))
            self.No_Hp.setPlainText(str(result[3]))
            self.Alamat.setPlainText(str(result[4]))
            c.close()
            conn.close()
        except:
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Critical)
            msgbox.setWindowTitle('Warning')
            msgbox.setText('Data tidak ditemukan')
            keluar = msgbox.exec_()

    def unggah(self):
        gig = self.Search_text.text()
        nama = self.Nama.toPlainText()
        nik = self.NIK.toPlainText()
        jenis_kelamin = self.Kelamin.currentText()
        nohp = self.No_Hp.toPlainText()
        alamat =  self.Alamat.toPlainText()
        try :
            conn = sqlite3.connect('Data/peserta.db')
            c = conn.cursor()
            sql = "UPDATE peserta SET Nama_Peserta = ?, NIK = ?, Jenis_Kelamin = ?, No_HP = ?, Alamat = ? WHERE Nama_Peserta = ?"
            insert = (str(nama), int(nik), jenis_kelamin, str(nohp), str(alamat), str(gig))
            c.execute(sql, insert)
            conn.commit()
            c.close()
            conn.close()
            ###<Jika Berhasil>####
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Information)
            msgbox.setWindowTitle('Info')
            msgbox.setText('Data telah terunggah')
            keluar = msgbox.exec_()
        except ValueError:
            ####<Jika Gagal>####
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Critical)
            msgbox.setWindowTitle('Failed')
            msgbox.setText('Data gagal diunggah, mohon diperiksa kembali')
            keluar = msgbox.exec_() 
    def hapus(self):
        org = self.Nama.toPlainText()
        msgbox = QMessageBox()
        msgbox.setIcon(QMessageBox.Question)
        msgbox.setWindowTitle('Alert')
        msgbox.setText('apakah kamu ingin menghapus data dari user '+str(org)+' ini...?')
        msgbox.setStandardButtons(QMessageBox.Yes | QMessageBox.No)
        tombol = msgbox.exec_()
        if tombol == QMessageBox.Yes:
            try :
                cuy = self.Nama.toPlainText()
                conn = sqlite3.connect('Data/peserta.db')
                c = conn.cursor()
                c.execute("DELETE from peserta WHERE Nama_Peserta = ?",(cuy,))
                conn.commit()
                c.close()
                conn.close
                #######<Jika Berhasil>#####
                msgbox = QMessageBox()
                msgbox.setIcon(QMessageBox.Information)
                msgbox.setWindowTitle('info')
                msgbox.setText('Data telah telah terhapus')
                keluar = msgbox.exec_()
            except :
                #######<Jika Gagal>######
                msgbox = QMessageBox()
                msgbox.setIcon(QMessageBox.Critical)
                msgbox.setWindowTitle('Warning')
                msgbox.setText('Data tidak ditemukan')
                keluar = msgbox.exec_()
        else:
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Information)
            msgbox.setWindowTitle('info')
            msgbox.setText('Data batal dihapus')
            keluar = msgbox.exec_()

    def setupUi(self, Input):
        Input.setObjectName("Input")
        Input.resize(502, 409)
        Input.setWindowTitle("Cari Data Peserta")
        self.label = QtWidgets.QLabel(Input)
        self.label.setGeometry(QtCore.QRect(-10, -10, 611, 491))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Cari = QtWidgets.QPushButton(Input)
        self.Cari.setGeometry(QtCore.QRect(330, 20, 91, 33))
        self.Cari.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Cari.setFont(font)
        self.Cari.setStyleSheet("background-color: #006680;\n"
"color:#ffffff;")
        self.Cari.setObjectName("Cari")
        #############Tombol Seacrh##############
        self.Cari.clicked.connect(self.pencarian)
        ########################################
        self.Alamat = QtWidgets.QPlainTextEdit(Input)
        self.Alamat.setGeometry(QtCore.QRect(50, 300, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Alamat.setFont(font)
        self.Alamat.setStyleSheet("")
        self.Alamat.setObjectName("Alamat")
        self.Kelamin = QtWidgets.QComboBox(Input)
        self.Kelamin.setGeometry(QtCore.QRect(50, 190, 101, 31))
        self.Kelamin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.Kelamin.setFont(font)
        self.Kelamin.setObjectName("Kelamin")
        self.Kelamin.addItem("")
        self.Kelamin.addItem("")
        self.No_Hp = QtWidgets.QPlainTextEdit(Input)
        self.No_Hp.setGeometry(QtCore.QRect(50, 240, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.No_Hp.setFont(font)
        self.No_Hp.setStyleSheet("")
        self.No_Hp.setObjectName("No_Hp")
        self.NIK = QtWidgets.QPlainTextEdit(Input)
        self.NIK.setGeometry(QtCore.QRect(50, 140, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.NIK.setFont(font)
        self.NIK.setStyleSheet("")
        self.NIK.setObjectName("NIK")
        self.Nama = QtWidgets.QPlainTextEdit(Input)
        self.Nama.setGeometry(QtCore.QRect(50, 80, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Nama.setFont(font)
        self.Nama.setStyleSheet("")
        self.Nama.setPlaceholderText("Nama")
        self.Nama.setObjectName("Nama")
        self.Dellete = QtWidgets.QPushButton(Input)
        self.Dellete.setGeometry(QtCore.QRect(230, 350, 111, 41))
        self.Dellete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Dellete.setFont(font)
        self.Dellete.setStyleSheet("background-color: #d40000;\n"
"color:#ffffff;\n"
"")
        self.Dellete.setObjectName("Dellete")
        ############Tombol Dellete##############
        self.Dellete.clicked.connect(self.hapus)
        ########################################
        self.Update = QtWidgets.QPushButton(Input)
        self.Update.setGeometry(QtCore.QRect(380, 350, 111, 41))
        self.Update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Update.setFont(font)
        self.Update.setStyleSheet("background-color: #00aa00;\n"
"color:#ffffff;")
        self.Update.setObjectName("Update")
        ##############Tombol Update#########
        self.Update.clicked.connect(self.unggah)
        ###################################
        self.Search_text = QtWidgets.QLineEdit(Input)
        self.Search_text.setGeometry(QtCore.QRect(70, 21, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Search_text.setFont(font)
        self.Search_text.setObjectName("Search_text")

        self.retranslateUi(Input)
        QtCore.QMetaObject.connectSlotsByName(Input)

    def retranslateUi(self, Input):
        _translate = QtCore.QCoreApplication.translate
        self.Cari.setText(_translate("Input", "Search"))
        self.Search_text.setPlaceholderText(_translate("Inpu", "Cari Nama.."))
        self.Alamat.setPlaceholderText(_translate("Input", "Alamat"))
        self.Kelamin.setItemText(0, _translate("Input", "Laki-Laki"))
        self.Kelamin.setItemText(1, _translate("Input", "Perempuan"))
        self.No_Hp.setPlaceholderText(_translate("Input", "No. Hp"))
        self.NIK.setPlaceholderText(_translate("Input", "NIK"))
        self.Dellete.setText(_translate("Input", "Dellete"))
        self.Update.setText(_translate("Input", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cari = QtWidgets.QWidget()
    ui = Ui_cari()
    ui.setupUi(cari)
    cari.show()
    sys.exit(app.exec_())
