# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from xlsxwriter.workbook import Workbook
from PyQt5.QtWidgets import QMessageBox

class Ui_Export(object):
    def expert(self):
        try :
            name = self.File.text()
            waktu_pertama = self.satu_awal.time().toString('HH:mm')
            waktu_kedua = self.satu_akhir.time().toString('HH:mm')
            waktu_ketiga = self.dua_awal.time().toString('HH:mm')
            waktu_keempat =self.dua_akhir.time().toString('HH:mm')
            sesi_1 = str(waktu_pertama)+'-'+str(waktu_kedua)
            sesi_2 = str(waktu_ketiga)+'-'+str(waktu_keempat)
            workbook = Workbook(str(name)+'.xlsx')
            worksheet = workbook.add_worksheet()
            conn = sqlite3.connect('Data/peserta.db')
            c = conn.cursor()
            sql = c.execute("SELECT * from peserta")
            worksheet.set_column('A:F', 20)
            celfor = workbook.add_format()
            celfor.set_align('center')
            worksheet.write('A1', 'Nama Peserta', celfor)
            worksheet.write('B1', 'NIK', celfor)
            worksheet.write('C1', 'Jenis Kelamin', celfor)
            worksheet.write('D1', 'No.HP', celfor)
            worksheet.write('E1', 'Alamat', celfor)
            worksheet.write('F1', 'Waktu Pelaksanaan', celfor)
            for baris, row in enumerate(sql):
                for kolom, value in enumerate(row):
                    worksheet.write_string(baris+1, kolom, value)
            inject = c.execute("SELECT * from peserta")
            jumlah = len(inject.fetchall())
            row = 1
            col = 5
            if jumlah % 2== 0:
                bagi = jumlah // 2
                for pertama in range(bagi):
                    worksheet.write(row, col, sesi_1)
                    row+=1
                for kedua in range(bagi):
                    worksheet.write(row, col, sesi_2)
                    row+=1
            else :
                tambah = jumlah + 1
                bagi = tambah // 2
                kurang = bagi - 1
                for pertama in range(bagi):
                    worksheet.write(row, col, sesi_1)
                    row+=1
                for kedua in range(kurang):
                    worksheet.write(row, col, sesi_2)
                    row+=1
            ###<Jika Berhasil>####
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Information)
            msgbox.setWindowTitle('Info')
            msgbox.setText('Data telah di ekspor')
            keluar = msgbox.exec_()
            workbook.close()
        except:
            #####Jika Gagal#######
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Critical)
            msgbox.setWindowTitle('Warning')
            msgbox.setText('Terdapat kesalahan, diperiksa kembali')
            keluar = msgbox.exec_()
    def setupUi(self, Input):
        Input.setObjectName("Input")
        Input.resize(502, 372)
        font = QtGui.QFont()
        font.setPointSize(18)
        Input.setFont(font)
        self.label = QtWidgets.QLabel(Input)
        self.label.setGeometry(QtCore.QRect(-20, -10, 611, 491))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.File = QtWidgets.QLineEdit(Input)
        self.File.setGeometry(QtCore.QRect(50, 40, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.File.setFont(font)
        self.File.setStyleSheet("")
        self.File.setPlaceholderText("Nama File")
        self.File.setObjectName("File")
        self.satu_awal = QtWidgets.QTimeEdit(Input)
        self.satu_awal.setGeometry(QtCore.QRect(90, 130, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.satu_awal.setFont(font)
        self.satu_awal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.satu_awal.setObjectName("satu_awal")
        self.satu_akhir = QtWidgets.QTimeEdit(Input)
        self.satu_akhir.setGeometry(QtCore.QRect(280, 130, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.satu_akhir.setFont(font)
        self.satu_akhir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.satu_akhir.setObjectName("satu_akhir")
        self.dua_awal = QtWidgets.QTimeEdit(Input)
        self.dua_awal.setGeometry(QtCore.QRect(90, 240, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.dua_awal.setFont(font)
        self.dua_awal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dua_awal.setObjectName("dua_awal")
        self.dua_akhir = QtWidgets.QTimeEdit(Input)
        self.dua_akhir.setGeometry(QtCore.QRect(280, 240, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.dua_akhir.setFont(font)
        self.dua_akhir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dua_akhir.setObjectName("dua_akhir")
        self.label_2 = QtWidgets.QLabel(Input)
        self.label_2.setGeometry(QtCore.QRect(140, 80, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Input)
        self.label_3.setGeometry(QtCore.QRect(140, 190, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.expor = QtWidgets.QPushButton(Input)
        self.expor.setGeometry(QtCore.QRect(100, 320, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(19)
        self.expor.setFont(font)
        self.expor.setStyleSheet("color:#ffffff;\n"
"background-color: #55d400;")
        self.expor.setObjectName("expor")
        self.expor.clicked.connect(self.expert)
        self.label_4 = QtWidgets.QLabel(Input)
        self.label_4.setGeometry(QtCore.QRect(242, 142, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Input)
        self.label_5.setGeometry(QtCore.QRect(242, 250, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Input)
        QtCore.QMetaObject.connectSlotsByName(Input)

    def retranslateUi(self, Input):
        _translate = QtCore.QCoreApplication.translate
        Input.setWindowTitle(_translate("Input", "Export to Excell"))
        self.label_2.setText(_translate("Input", "Waktu Pelaksanaan Sesi 1"))
        self.label_3.setText(_translate("Input", "Waktu Pelaksanaan Sesi 2"))
        self.expor.setText(_translate("Input", "Export"))
        self.label_4.setText(_translate("Input", "-"))
        self.label_5.setText(_translate("Input", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Export = QtWidgets.QWidget()
    ui = Ui_Export()
    ui.setupUi(Export)
    Export.show()
    sys.exit(app.exec_())
