# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Input_peserta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
class Ui_Input(object):
    ###############<Connect to Database>###################
    def save(self):
        try :
            nama = self.Nama.toPlainText()
            nik = self.NIK.toPlainText()
            jenis_kelamin = self.Kelamin.currentText()
            alamat = self.Alamat.toPlainText()
            nohp = self.No_Hp.toPlainText()
            insert = (str(nama), int(nik), jenis_kelamin, str(nohp), str(alamat))
            conn = sqlite3.connect('Data/peserta.db')
            c = conn.cursor()
            sql = "INSERT INTO peserta(Nama_Peserta, NIK, Jenis_Kelamin, No_HP, Alamat)"+ \
            "VALUES" +str(insert)
            data = c.execute(sql)
            conn.commit()
            c.close()
            conn.close()
            ###<Jika Berhasil>####
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Information)
            msgbox.setWindowTitle('Info')
            msgbox.setText('Data telah ditambahkan di database')
            keluar = msgbox.exec_()
        except ValueError:
            msgbox = QMessageBox()
            msgbox.setIcon(QMessageBox.Critical)
            msgbox.setWindowTitle('Warning')
            msgbox.setText('Terdapat kesalahan, diperiksa kembali')
            keluar = msgbox.exec_()
    def bersih(self):
        self.Nama.setPlainText('')
        self.NIK.setPlainText('')
        self.Alamat.setPlainText('')
        self.No_Hp.setPlainText('')

    def setupUi(self, Input):
        Input.setObjectName("Input")
        Input.resize(502, 372)
        self.label = QtWidgets.QLabel(Input)
        self.label.setGeometry(QtCore.QRect(-20, -10, 611, 491))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Nama = QtWidgets.QPlainTextEdit(Input)
        self.Nama.setGeometry(QtCore.QRect(40, 30, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Nama.setFont(font)
        self.Nama.setStyleSheet("")
        self.Nama.setPlaceholderText("Nama")
        self.Nama.setObjectName("Nama")
        self.NIK = QtWidgets.QPlainTextEdit(Input)
        self.NIK.setGeometry(QtCore.QRect(40, 90, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.NIK.setFont(font)
        self.NIK.setStyleSheet("")
        self.NIK.setObjectName("NIK")
        self.Kelamin = QtWidgets.QComboBox(Input)
        self.Kelamin.setGeometry(QtCore.QRect(40, 140, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.Kelamin.setFont(font)
        self.Kelamin.setObjectName("Kelamin")
        self.Kelamin.addItem("")
        self.Kelamin.addItem("")
        self.Kelamin.addItem("")
        self.No_Hp = QtWidgets.QPlainTextEdit(Input)
        self.No_Hp.setGeometry(QtCore.QRect(40, 190, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.No_Hp.setFont(font)
        self.No_Hp.setStyleSheet("")
        self.No_Hp.setObjectName("No_Hp")
        self.Alamat = QtWidgets.QPlainTextEdit(Input)
        self.Alamat.setGeometry(QtCore.QRect(40, 250, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Alamat.setFont(font)
        self.Alamat.setStyleSheet("")
        self.Alamat.setObjectName("Alamat")
        self.Clear = QtWidgets.QPushButton(Input)
        #########tombol Clear#################
        self.Clear.clicked.connect(self.bersih)
        #####################################
        self.Clear.setGeometry(QtCore.QRect(30, 318, 101, 31))
        self.Clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Clear.setFont(font)
        self.Clear.setObjectName("Clear")
        self.Submit = QtWidgets.QPushButton(Input)
        self.Submit.setGeometry(QtCore.QRect(360, 310, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Submit.setFont(font)
        self.Submit.setStyleSheet("background-color: #0055d4;\n"
"color: rgb(255, 255, 255);")
        self.Submit.setObjectName("Submit")
        self.Submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        ############Tombol Submit##########
        self.Submit.clicked.connect(self.save)
        ##################################
        self.retranslateUi(Input)
        QtCore.QMetaObject.connectSlotsByName(Input)

    def retranslateUi(self, Input):
        _translate = QtCore.QCoreApplication.translate
        Input.setWindowTitle(_translate("Input", "Input Data Peserta"))
        self.NIK.setPlaceholderText(_translate("Input", "NIK"))
        self.Kelamin.setItemText(0, _translate("Input", "Jenis Kelamin..."))
        self.Kelamin.setItemText(1, _translate("Input", "Laki-Laki"))
        self.Kelamin.setItemText(2, _translate("Input", "Perempuan"))
        self.No_Hp.setPlaceholderText(_translate("Input", "No. Hp"))
        self.Alamat.setPlaceholderText(_translate("Input", "Alamat"))
        self.Clear.setText(_translate("Input", "Clear"))
        self.Submit.setText(_translate("Input", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Input = QtWidgets.QWidget()
    ui = Ui_Input()
    ui.setupUi(Input)
    Input.show()
    sys.exit(app.exec_())
   
